### ISSUE TITLE
Verify number formatting

### ISSUE THREAD

**Issue by eoglethorpe** [toggle-corp/palika-profile#25]
There are three types of numerical values in the profiles: Integer, Decimal, Pct. See explanations and examples below. Note that this reads in the **raw value** of values stored in the Excel sheet, and not whatever formatting may be applied.

The logic for these values is:

- int: display value as is while rounding down any decimals. apply appropriate thousands separators for nepali/eng
- dec: default of 2 decimal points, and will fill with any missing 0s. if there are more than 2 decimal points, round up/down depending on if < > .5
- pct: apply much the same logic as dec formatting, but apply a % sign at the end. assumes that values are in decimals and converts to whole numbers.

sample output:

Eng

> 
> Num
> 
> 1  >> 1
> 1000  >> 1,000
> 1000000  >> 1,000,000
> .55 >> 0
> 5.5 >> 5
> 
> Dec
> 
> 0 >> 0.00
> .4 >> 0.40
> 5.5 >> 5.50
> 6 >> 6.00
> 6444.23 >> 6444.23
> 6.889 >> 6.89
> 
> Pct
> 
> 0 >> 0.00%
> .344455 >> 34.45%
> .3 >> 30.00%
> 1 >> 100.00%
> Decimal value is greater than 1: 1.3
> 1.3 >> 130.00%

Nepali
 
> Num
> 
> 1  >> १
> 1000  >> १,०००
> 1000000  >> १०,००,०००
> .55 >> ०
> 5.5 >> ५
> 
> Dec
> 
> 0 >> ०.००
> .4 >> ०.४०
> 5.5 >> ५.५०
> 6 >> ६.००
> 6444.23 >> ६४४४.२३
> 6.889 >> ६.८९
> 
> Pct
> 
> 0 >> ०.००%
> .344455 >> ३४.४५%
> .3 >> ३०.००%
> 1 >> १००.००%
> 1.3 >> १३०.००%

This logic is applied to the following sections of the profiles:

- FnF: int
- typo: pct
- recon and retro: int
- const material: req quant (int), cost (dec), wage (dec)
- other sects: int
- land issues: int
- tech staff: int
- trainings: int

**Comment by Yuvee04** [comment]
we think wage and cost would be better if they are in integer. 
Even better would be if the generators would respond to respective uid for the field in the excel.

**Comment by eoglethorpe** [comment]
@Yuvee04 please check on the next update

**Comment by Yuvee04** [comment]
Yes it is fine. Thank you.
