### ISSUE TITLE
Facts and Figure

### ISSUE THREAD

**Issue by Yuvee04** [toggle-corp/palika-profile#28]
In facts and Figure section, Index should be start from the mid part of the box.
similar issues are also in Nepali version too. 
![Issue](https://user-images.githubusercontent.com/49233529/55707923-74f39400-5a04-11e9-9431-5a94ec6135dc.png)
![Capture 2](https://user-images.githubusercontent.com/49233529/55791287-e3585500-5add-11e9-99cd-5f277ca0c135.PNG)

**Comment by Yuvee04** [comment]
I think i cannot clearly mention the actual issue to you. 
The requirement is that in the index section the damage grade should start from the middle of the box. as per the mark shown in the picture attached. (For both Nepali and English version)

![image](https://user-images.githubusercontent.com/49233529/55851245-9923b200-5b77-11e9-8f5f-fa875b374ec9.png)

**Comment by Yuvee04** [comment]
It is not revised as per the comment. it seems as previously.  Need to make the changes as per the comment mention above.

**Comment by AdityaKhatri** [comment]
@Yuvee04 
![image](https://user-images.githubusercontent.com/7893887/56416787-9d577a00-62b1-11e9-98e2-bd148253b6ab.png)

is this okay?
