### ISSUE TITLE
File Name when we export the profile 

### ISSUE THREAD

**Issue by Yuvee04** [toggle-corp/palika-profile#33]
Right now when we generate the palika profile it will be exported by the palika code. if the palika profile will be generated with the following naming structures then it would be easier.
1. District Name_Palika Name

**Comment by thenav56** [comment]
@Yuvee04 Should we append the language there too?
Like this `Lalitpur__Mahalaxmi_Nagarpalika_en.pdf`?

**Comment by Yuvee04** [comment]
yes, that would be great.

**Comment by Yuvee04** [comment]
Great. its is working as per the requirement. Thank you.
