### ISSUE TITLE
Heading of the palika profile for Nepali version

### ISSUE THREAD

**Issue by Yuvee04** [toggle-corp/palika-profile#36]
District name, palika name, month and year in the nepali version is not in nepali although the uploaded file has the nepali. 
![Capture1](https://user-images.githubusercontent.com/49233529/55791037-5e6d3b80-5add-11e9-80ef-b408007768d5.PNG)

**Comment by Yuvee04** [comment]
Great, Name of District, Palika Name and month name are in Nepali.  Year should also be in nepali in nepali version.  
![Issue 5](https://user-images.githubusercontent.com/49233529/56181219-3c6b4000-602c-11e9-8f1f-455aea612061.PNG)

**Comment by eoglethorpe** [comment]
@Yuvee04 did you put in the nepali year in the excel file under #header_year? otherwise if you want it to be transliterated, we can just convert the english year numbers to nepali

**Comment by Yuvee04** [comment]
@eoglethorpe  yes i had kept the nepali translated in the excel file (title sheet) under #header_year

**Comment by eoglethorpe** [comment]
can you check and see if it’s actually being read as Nepali #s and not just being represented as such? This is what I’d guess

**Comment by Yuvee04** [comment]
I exported and had gone through this. the main thing is that i had input the year (data) in Nepali but it is showing in english. for example: i had input data as २०७५ and it is showing 2075.) we need is २०७५

![image](https://user-images.githubusercontent.com/49233529/56335529-9e5aaf80-61bc-11e9-9755-5d2a62cb460b.png)

![image](https://user-images.githubusercontent.com/49233529/56335718-4b352c80-61bd-11e9-9643-de147f9a2539.png)

**Comment by eoglethorpe** [comment]
yeah that’s an Excel issue… I’ll look into seeing if we can read the cell’s value differently otherwise I’d recommend a conversion method for the regular english date > nepali (+66 years) and then convert the characters. thoughts?

**Comment by eoglethorpe** [comment]
the fix is to translate english #s to nepali if they're present, otherwise we keep the regular nepali if it's read as a string in Excel
