### ISSUE TITLE
Nepali Translation on Nepali version of Palika profile

### ISSUE THREAD

**Issue by Yuvee04** [toggle-corp/palika-profile#43]
Nepali version of palika profile has not pulled the data from the suffix #....np. i had colored the part which need to be in nepali in the following attachement. 
[Gorkha__Aarughat_Gaunpalika__np.pdf](https://github.com/toggle-corp/palika-profile/files/3067915/Gorkha__Aarughat_Gaunpalika__np.pdf)

**Comment by eoglethorpe** [comment]
yep my bad, it should all be there except for the maps which i will look into later

**Comment by Yuvee04** [comment]
This part is almost completed. the things which are not done, i had made an another issues and updated. so it can be closed.
