### ISSUE TITLE
Footer for the Housing Reconstruction and Retrofit updates section

### ISSUE THREAD

**Issue by Yuvee04** [toggle-corp/palika-profile#48]
Need to add the footer for the Housing Reconstruction and Retrofit Updates Section. 
Footer will be not long. it will be: Data updated on: DD/MM/YY). The place to be shown is marked in the attachment. 
![image](https://user-images.githubusercontent.com/49233529/56120592-273fd400-5f8e-11e9-9874-15bfe3f6ddca.png)

**Comment by thenav56** [comment]
@Yuvee04 Can you provide further information on where I can get the Data for `updated on`.
Thanks,

**Comment by Yuvee04** [comment]
Need to add new line for this. May be in title sheet section. it is totally new idea to put the footer for this section. we just need to put footer as: Data updated on: DD/MM/YY) 
we will update the date as per the requirement during the export time.

**Comment by eoglethorpe** [comment]
@thenav56 i'll add a column and a row and then let you know

**Comment by thenav56** [comment]
@Yuvee04 Use the new xlsx format to provide the
- prefix `#recon_&_retrofit_panel_footer` (Titles)
- palika data `#recon_footer_date` and `#recon_footer_date_np`
