### ISSUE TITLE
T.A. Activities Map Section of Nepali Version

### ISSUE THREAD

**Issue by Yuvee04** [toggle-corp/palika-profile#52]
In Nepali Version, there are something need to be translate in Nepali. I had colored with yellow color. 

1. Count of TA activities (by ward): none, 1, 2, 3, 4, 5  6, 7 
2. *Note (1) indicates wards in municipal
3. Name of district 
4. Ward numbers shown in Map. 
 If you mention the place where i need to translate then i can do that. 
![image](https://user-images.githubusercontent.com/49233529/56182459-16489e80-6032-11e9-804d-fb9d65eb0d4f.png)

**Comment by eoglethorpe** [comment]
noted, thanks

**Comment by eoglethorpe** [comment]
see #55
