### ISSUE TITLE
Map Generation in Some Palikas

### ISSUE THREAD

**Issue by Yuvee04** [toggle-corp/palika-profile#53]
In Some palika Maps are not generated. i had mention this issue in the skype too. It is showing that Map could not be generated. 
 (Godawari and konjyosom palika of lalitpur is the example for the problems in map generation. 
![Issue 2](https://user-images.githubusercontent.com/49233529/56205945-e10c7280-606a-11e9-85cd-61744600c922.PNG)

**Comment by eoglethorpe** [comment]
@Yuvee04 i believe this is a result of the provided shapefiles not having the required palika codes to match, but i'll double check

**Comment by eoglethorpe** [comment]
@Yuvee04 i did some checks and it looks like the codes are missing in the shape files you've provided us. could you resend a complete file? (ideally geojson and not a shapefile). attached is an overview of counts between the codes in the data you most recently and what's in the shapefile.

[palika counts.xlsx](https://github.com/toggle-corp/palika-profile/files/3097808/palika.counts.xlsx)

**Comment by Yuvee04** [comment]
@eoglethorpe  i think the (geojson) shape files which i had shared to you as per your request will also cover this issues too. 

Just for information to make clear.
(As per the above comment you shared along with the palika count file. there is two codes that are missing and two codes that are double. 
double code: 12002, 20003
missing code: 25002. 25003
double codes should be replaced by the missing code. which has been done by uttam jee in the (geojson) shape file shared to you in the previous issue.)
